<?php

namespace AppBundle\Repository;

/**
 * AdminUserMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
