<?php

namespace AppBundle\Repository;

/**
 * OrderdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderdetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
