<?php

namespace AppBundle\Repository;

/**
 * ProductDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
