<?php

namespace AppBundle\Repository;

/**
 * ProductBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductBundleRepository extends \Doctrine\ORM\EntityRepository
{
}
